### ISSUE TITLE
Questions about writing an extension

### ISSUE THREAD

**Issue by bbtfr** [lwe/simple_enum#113]
Hi, lwe

Recently, I'm working on writing 2 simple_enum extensions, https://github.com/bbtfr/simple_enum-persistence and https://github.com/bbtfr/simple_enum-multiple

There are some questions about how to write an extension:

1. Seems it's hard to add an additional option or to change existing options for `as_enum`, only way to do that is overriding `as_enum`.
E.g.: I want to add an additional option `persistence`, it's a shortcut for several other options
https://github.com/bbtfr/simple_enum-persistence/blob/master/lib/simple_enum/persistence/extension.rb
I have to override `as_enum`.

2. I'm confusing with `module_eval` and `simple_enum_module.module_eval`  https://github.com/lwe/simple_enum/blob/master/spec/simple_enum/attribute_spec.rb#L17
What's `simple_enum_module` for? and what's the difference?
I've remove all the simple_enum_module, like this:
https://github.com/bbtfr/simple_enum/blob/master/lib/simple_enum/attribute.rb#L43
It still works

**Comment by bbtfr** [comment]
And there is no way for an extension to access options.

**Comment by lwe** [comment]
Hey, thanks for all the inputs and questions.

1. Yes, indeed that's true, this is also how support for mongoid works at the moment, that the user has to include `SimpleEnum::Mongoid` in the model and then can use `as_enum` with additional options. Isn't using something similar like that an option for you too? Do you have a proposal how we could provide hooks into that in SE::Attribute that could help you write your extensions?
2. `module_eval` vs `simple_enum_module.module_eval`, this allows to use `super` to override a method from simple enum, so when evaluating the methods directly on the class itself, they are added there - when doing it on the module, they are added to the ancestor tree and can be overridden by other methods. In the end it works the same you are correct, but you can't do this:
   ```ruby
   class MyModel
     as_enum :gender, [:female, :male]

     # ^^ totally silly use case, but by not adding it to the class itself, but as ancestors
     # stuff like that is possible
     def gender
       super == :female ? Genders::FEMALE : Genders::MALE
     end
   end
   ```

**Comment by lwe** [comment]
^^ it's very, very nice to see that you are building stuff on top of SimpleEnum, when your gems are ready, let me know so I can link to them in the README

**Comment by bbtfr** [comment]
:smile: Oh, I see, It's very convenient since people can use super.

**Comment by bbtfr** [comment]
I've created a PR, #114

**Comment by bbtfr** [comment]
Thanks for your help, my extensions are ready to use:
[SimpleEnum::Multiple](https://github.com/bbtfr/simple_enum-multiple): multi-select enum support
[SimpleEnum::Persistence](https://github.com/bbtfr/simple_enum-persistence): data persistence (store enum values in database)

**Comment by lwe** [comment]
FYI, I've pushed 2.3.0 to Rubygems - ensure your gems depend on `=> 2.3.0`

**Comment by bbtfr** [comment]
OK, Thanks
