### ISSUE TITLE
Mongoid and using where

### ISSUE THREAD

**Issue by Bartuz** [lwe/simple_enum#116]
Using mongoid I can't find objects with via enums. 

```
Post.create(status: pending)
=> #<Calculation _id: 560c51a3cdea875eb5000000, status_cd: 0>
Post.where(status: :pending).count
=> 0
Post.where(status_cd: 0).count
=> 1
```

**Comment by Bartuz** [comment]
I started using different gem. works there. https://github.com/thetron/mongoid-enum/pull/25

**Comment by lwe** [comment]
Yes, there are named scopes es exposed like: `Post.pendings` for that, if you need to use the where clause, you can do something like

```ruby
Post.where(status_cd: Post.status[:pending])
```

However we are planning a `with_enum` method or something similar, where it's possible to write `with_enum(status: :pending)` directly, see the thread in #95.
