### ISSUE TITLE
Get value with the enum key

### ISSUE THREAD

**Issue by martinezcoder** [lwe/simple_enum#117]
In previous versions of simple_enum (e.g. v1.6.9), when I had some code like this:

````
class MyEntry
  include Mongoid::Document
  include SimpleEnum::Mongoid

  as_enum :status, %i{unresolved resolved}, prefix: true
````

It was possible to execute this kind of code:

````
if @my_entry.status == MyEntry.status_resolved 
````

In newer versions ( => v2.0.0 ) this code raises an error

````
NoMethodError: undefined method `status_resolved' for MyEntry:Class
````

It was very useful to have this class methods to avoid the programmer to have typo errors. 

In the version notes it says that now we must use MyEntry.statuses[:resolved], but this won't avoid typo errors of this kind:

`````
if @my_entry.status == MyEntry.statuses[:resolve]
`````

Note that I have introduced a type error (resolve instead of resolved) but the code won't raise any error. Also, if some day I change this status name, it will be very dangerous to repair all the code. With last version was easier, because after changing the name I will get a raise error in every mistake.

**Comment by lwe** [comment]
Yes, for this purpose we have added MyEntry.statuses.fetch(:resolve) which raises an exception (like Hash.fetch) when the key does not exist. Does that work for you?

**Comment by martinezcoder** [comment]
yes, thanks!

**Comment by lwe** [comment]
You are welcome :+1:
