### ISSUE TITLE
How to display text file result from batch jobs?

### ISSUE THREAD

**Issue by kan1207** [lwe/simple_enum#123]
I have some scheduled batch jobs running automatically during the night and will show the results in separate .txt files. Is there anyway to grab the data from the .txt file and consolidate them to display in kibana? Any tools or reference .conf?

Here is the case:
I have two data : Job Name.txt & Job Status.txt . No matter they're in a same file or separate. I hope to pop the status in proper way in kibana.

I have found the mapper-attachment plugin and logstash-input-file plugin, yet, I am not sure how should it be work out

Thanks

**Comment by lwe** [comment]
Looks like you picked the wrong project to report this bug. simple_enum is not affiliated with kibana or one of it's plugins.
