### ISSUE TITLE
Negation of selectors

### ISSUE THREAD

**Issue by Startouf** [lwe/simple_enum#124]
I don't understand how I could negate one of the simple_enum selectors

In Mongoid I'm trying 

```
scope :not_cancelled, -> {
    not(my_enum_cancelleds.selector)
  }
```

But I get some 

> Mongo::Error::OperationFailure Exception: $not needs a regex or a document (2)

The selector being

```
selector: {"my_enum_cd"=>{"$not"=>1}}
```

What's the correct way to go about it ? (Not sure this is a SimpleEnum specific problem)

**Comment by lwe** [comment]
Not much of a mongodb user myself, but according to https://docs.mongodb.com/manual/reference/operator/query/not/ it should probably be an expression like:

```
{ "my_enum_cd" => { "$not" => { "eq" => 1 } } }
```

**Comment by aledalgrande** [comment]
I would write that as:

```ruby
scope :not_a_baseball_fan, -> {
  not_in(User.baseball_fans.selector)
}
```

**Comment by Startouf** [comment]
Thanks I wasn't aware of the `not_in` method, totally feels right when reading.
