### ISSUE TITLE
Cucumber tests and translated enums in action steps

### ISSUE THREAD

**Issue by Startouf** [lwe/simple_enum#125]
I am writing cucumber tests, a way of testing that consists of decoupling the test scenarios (written in Gherkin/natural english) from the steps (written in the programming language like Ruby here)

I'm wondering how to handle enums in this case. I am testing my search engine, so I need to feed my database with some entries (for example companies here).

My actual company model is like

``` ruby
class Company
  field :name
  as_enum :size, SIZE_LIST # [:under_10,  :under_10000, ...]
  as_enum :sector, SECTOR_LIST [:it_webapp_media,  :tourism_entertainment, ...]

end
```

However, in Gherking I would not write the enum symbols/strings, but directly their translated values

``` gherkin
Background:
    Given the following companies exist:
        | name   | sector                | size |
        | Facebook       | IT, Web/App, media | >10000       |
        | Casterman      | Tourism & entertaining    | >10000       |
        | My Startup          | Tourism & entertaining    | <10       |
```

And my step would be defined like this

``` ruby
Given(/^the following compan(ies|y) exists?:$/) do |companies|
  companies.hashes.each do |options|
    FactoryGirl.create(:company, options)
  end
end
```

However I need to first inverse translate the translated enums to their enum symbol, ie the transformation of `IT, Web/App, media` into the symbol `:it_webapp_media`that I need for my factory.

Any tip ?

**Comment by seanfcarroll** [comment]
+1

**Comment by lwe** [comment]
There is no out-of-the-box way to handle this by either Rails, I18n or simple_enum - you'd require to create the reverse lookup hash somehow yourself and then rewrite it.

**Comment by Startouf** [comment]
Just for info, I ended up creating the reverse lookup hashes as you suggested. 
Maybe a helper like `SimpleEnum.symbolize(clazz, :enum, translated_value)` could be an alternative. But anyway, the only use case I can think of is for testing so I guess it's okay.

```ruby
Given(/^the following companies exist$/) do |companies|
  size_to_sym = I18n.t(:size, scope: :enums).invert
  sectors_to_sym = I18n.t(:sector, scope: :enums).invert

  companies.map_column!('Sector') { |sector| sectors_to_sym[sector] }
  companies.map_column!('Size') { |size| size_to_sym[size] }

  companies.hashes.each do |attributes|
    FactoryGirl.create(:company, attributes)
  end
end
```

**Comment by lwe** [comment]
(y) cool, glad you did find a solution. Will close this ticket in the meantime, okay? With the FAQ / Support tag it still could prove useful for others working on a similar solution.
