### ISSUE TITLE
values_at doesn't work with mongoid

### ISSUE THREAD

**Issue by nitvik** [lwe/simple_enum#126]
This does not work with mongoid.
`User.genders.values_at(:female, :male)`

**Comment by aledalgrande** [comment]
Hey @nitvik mind providing an output log and what version of Mongoid you're using?

**Comment by drobny** [comment]
@aledalgrande I think the Readme might be outdated in the Mongoid Quick start section. It says put this in the Gemfile:

`gem 'simple_enum', '~> 2.0.0' , require: 'simple_enum/mongoid'`

but version 2.0.x of simple_enum does not include the `values` and `values_at` methods referred to in other parts of the Readme which potentially is why @nitvik is getting those errors.

Can we just use the latest version of the gem (I tried very briefly and seemed to work ok), i.e. change the Readme to
 
`gem 'simple_enum', require: 'simple_enum/mongoid'`

or do you think this would cause other issues?

**Comment by aledalgrande** [comment]
Seems like it was introduced in `2.1.0`. I suggest updating the README to the latest version of the gem, instead of dropping the version, which could introduce other issues like this one. 👍 @drobny?

**Comment by lwe** [comment]
👍  yes, suggest to update the readme to read either `~> 2.1.0` or `~> 2.0`, because specifying a version is very important IMO in the Gemfile.

**Comment by nitvik** [comment]
Thanks, I upgraded the gem to 2.1.0 and the problem was fixed. I was using 2.0.0.
