### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by aledalgrande** [lwe/simple_enum#127]
I have used this gem in several Rails apps, would be a shame if it died down. I see the last commit was made about a year ago. Need some help?

**Comment by lwe** [comment]
Hey, yes, some help would be awesome. My day job involves less Ruby nowadays - in addition Rails added a similar feature...

**Comment by aledalgrande** [comment]
From what I understand the new feature is AR only, so Mongoid still needs this gem. Will see if I can send some pull requests and help with issues!

**Comment by lwe** [comment]
Hey @aledalgrande, good point - also simple_enum has a few features on top, which AR does not support.

Looking forward to your pull requests 👌 all help is greatly appreciated!

Thanks, Lu
