### ISSUE TITLE
New labels

### ISSUE THREAD

**Issue by aledalgrande** [lwe/simple_enum#128]
@lwe what do you think of adding a couple of labels to organize work?

- `up-for-grabs`: issue needs work and it is up for grabs for any person who wants to contribute to open source;
- `PR-attached`: Rails-style informational label that prevents duplication of work.

**Comment by lwe** [comment]
Totally, good idea 👍

**Comment by aledalgrande** [comment]
Hey @lwe do you have any time to create the labels? Thanks.

**Comment by lwe** [comment]
Hi @aledalgrande, better late than never right? done, thanks for the patience.
