### ISSUE TITLE
Report: Some of ActiveRecord::Dirty methods are deprecated but it doesn't support

### ISSUE THREAD

**Issue by ykamez** [lwe/simple_enum#146]
## Report
HI. Right now, some of ActiveRecord::Dirty methods are deprecated in Rails 5.1 and will be removed in Rails 5.2 according to [this pr](https://github.com/rails/rails/pull/25337):

ref: https://www.ombulabs.com/blog/rails/upgrades/active-record-5-1-api-changes.html

However, in simple_enum, new methods as described below are NOT supported.

- `saved_change_to_attribute?` (instead of `attribute_changed?`)
- `attribute_before_last_save` (instead of `attribute_was `)

## What is problem?
It could cause some error when updating from Rails 5.1 or older to Rails 5.2+.

For example, 

model: User, column: state_cd (enum)

- before

```ruby
state_changed? #=> true or false
```

- after update(changing method name)
simple_enum doesn't support new methods, so it cause error like below.

```ruby
saved_change_to_state? # => it doesn't work.

```
I got error.

```ruby
        NoMethodError:
            undefined method `saved_change_to_state?' for #<User:0x00005xxa>
```

So I have to write like this.
```ruby
saved_change_to_state_cd?  #=> true or false
```

**Comment by ykamez** [comment]
@lwe  Could you check this issue?

**Comment by drobny** [comment]
@ykamez I will try and find some time to look into this and get back to you

**Comment by lwe** [comment]
Thanks y'all and especially @drobny for picking this up.

**Comment by drobny** [comment]
@ykamez can you confirm ☝️ works for you, need to try and sort CI as it is failing (unrelated to my change)

**Comment by ykamez** [comment]
Thanks @drobny 
Changes in [this pr](https://github.com/lwe/simple_enum/pull/147/files) looks good to me.

**Comment by lwe** [comment]
👍 will merge and release this weekend. Thanks y’all

**Comment by ykamez** [comment]
@drobny  Please merge the latest master branch.
