### ISSUE TITLE
prefix: true as default

### ISSUE THREAD

**Issue by abacha** [lwe/simple_enum#77]
in the README you recommend to use it to avoid conflicts
don't you think it should be default?

**Comment by bikramwp** [comment]
I'd like to suggest having a `Simple.prefix = true`  option that can be used app-wide. Would you accept a pull-request for such an option?

**Comment by bikramwp** [comment]
I'd like to suggest having a `Simple.prefix = true` option that can be used app-wide. Would you accept a pull-request for such an option? It would still default to `false`, so it would have to be set explicitly.

**Comment by lwe** [comment]
Sure thing, yes
