### ISSUE TITLE
Protection from passing wrong symbols/strings to enums.

### ISSUE THREAD

**Issue by mainameiz** [lwe/simple_enum#96]
First of all, thank you for writing such a good gem. :-)

```ruby
class Model < AR
  as_enum :state, {
    accept: 0,
    reject: 1
  }
end

Model.states[:wrong_state] => nil
```

It seems to be better to raise an exception in such cases.

**Comment by matthewrudy** [comment]
maybe we just want `Model.states.fetch(:wrong_state)`
and behave like `Hash#fetch`

**Comment by lwe** [comment]
You can use the _whiny_ accessor, that works like that

```ruby
class User < ActiveRecord::Base
  as_enum :gender, %w{male female}, accessor: :whiny
end
User.new(gender: "dunno") # => raises ArgumentError
```

**Comment by lwe** [comment]
and you are welcome :)

**Comment by mainameiz** [comment]
@lwe Yes, whiny accessor works great, but image we write a scope 
```ruby
-> { where(state_cd: self.states[:wrong_state]) }
```
It will silently paste `nil` in sql query. To protect from such cases I suggest to raise an error or to implement #fetch method as @matthewrudy suggests. I cant image situations where it can be prefered to return `nil` for not existing enums.

Thank you for writing such a good gem :-)

**Comment by lwe** [comment]
Ah, now I get it, sorry. Yes, please, feel free to provide a pull request with a `fetch` implementation, would gladly accept it.

**Comment by mainameiz** [comment]
@lwe ok!

**Comment by mainameiz** [comment]
Done! #104

**Comment by lwe** [comment]
Hey, thanks!

**Comment by lwe** [comment]
FYI, I'm closing this issue now, ok?

**Comment by mainameiz** [comment]
Ok, thanks you! :-)

**Comment by aayush-practo** [comment]
Hey, @mainameiz 
Check the two situations:
- my first attribute is `settlement_status` and second attribute `status`. Here are the enums
```ruby
class ModelA <AR
   as_enum :settlement_status, [:initiated, :settlementInProgress, :settled, :failure, :queuedInNextCycle], map: :string, source: :settlementStatus, accessor: :whiny
end

class ModelB < AR
  validates :status, presence: true
  as_enum :status, [:active, :expired], map: :string, source: :status, accessor: :whiny
end
```
When making new object of ModelB with invalid value for status, it throws error, but does nothing for ModelA, it creates the object and commits it to the database

for example
```ruby
@model_a = ModelA.new(settlement_status: "abc")
@model_a.save
```
it is committed successfully

for
```ruby
 @model_b = ModelB.new(status: "abc")
ArgumentError: abc is not a valid enum value for status
```

Please help me with it
