### ISSUE TITLE
Enum with multiple values selected

### ISSUE THREAD

**Issue by Startouf** [lwe/simple_enum#97]
This would probably mean a lot of work, but I'd like to have enums with multiple values selected, for example in Mongoid, taking advantage of `field ..., type: Array`.

I have given an example of what I want to do in this [StackOverflow](http://stackoverflow.com/questions/29584655/rails-fill-a-mongoid-array-field-with-selected-options-of-a-select-as-symbols)

For example, let's say I want to classify my projects, but a project can be related to many domains/areas. In this case I'd like to have a "multiple selected value enum"
```ruby
class Project
  # Instead of "field :domains, type: Array" and boring validation stuff
  as_multiple_enum :domains, [:programming, :electronics, :translation]
```

And a small user scenario
```ruby
p = Project.new(title: 'Design a new card for a PC and code a driver')
p.programming!
p.electronics!
p.domains # [:electronics, :programming]

p.title += '...and write the manual in many languages'
p.translation!
p.domains # [:electronics, :programming, :translation]

# Actually someone else is going to take care of coding the driver
p.not_programming!
p.domains # [:electronics, :translation]
```

**Comment by lwe** [comment]
AFAIK, there's a fork of simple_enum built for this - also with the new extension mechanism it should be rather simple to create a plugin for this. To be honest I'd really like to keep this out of the "core" of simple_enum - also see #89 and #90.

**Comment by Startouf** [comment]
Oh sorry I should have searched before...
