### ISSUE TITLE
Class method conflicts with Ruby class method

### ISSUE THREAD

**Issue by hraynaud** [lwe/simple_enum#98]
Hi Quick question I have an enum defined on a Payment model as follows:  

as_enum :method, [:online, :check, :cash]

In previous version i could do 

Payment.online

In the current version 

Payment.methods[:online]

Obviously i could change the enum name to something like "meths" but I was wondering if there was a built in solution of conflicting class method names similar to the apparent solution for instance method names.

**Comment by lwe** [comment]
Hey, no, not for the class methods - this is kind of a limitation at the moment and maybe it would make sense to add some checks for _invalid / common names_ to avoid issues like this beforehand. The only solution at the moment:

```ruby
as_enum :payment_method, %w{online check cash}, column: 'method_cd'
```

This is basically the "built in" version on how to handle this :)

**Comment by hraynaud** [comment]
Hi Lukas

Thanks for the quick response. The suggested solution specifying the column should work. Thanks again.

Herby

**Comment by lwe** [comment]
Hey Herby, you're welcome!
